# Generated by Django 4.1.13 on 2025-02-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_discount_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='percentage',
        ),
        migrations.AddField(
            model_name='discount',
            name='amount_off',
            field=models.PositiveIntegerField(blank=True, help_text='Положительное целое число, представляющее сумму скидки в минимальных единицах валюты (например, центы).', null=True, verbose_name='Скидка в валюте'),
        ),
        migrations.AddField(
            model_name='discount',
            name='currency',
            field=models.CharField(blank=True, help_text='Трехбуквенный код ISO для валюты (требуется, если указан amount_off).', max_length=3, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='discount',
            name='duration',
            field=models.CharField(choices=[('forever', 'Forever'), ('once', 'Once'), ('repeating', 'Repeating')], default='once', help_text='Как долго будет действовать скидка: forever, once или repeating.', max_length=10, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='discount',
            name='duration_in_months',
            field=models.PositiveIntegerField(blank=True, help_text="Требуется только если duration='repeating'. Количество месяцев, в течение которых действует скидка.", null=True, verbose_name='Длительность в месяцах'),
        ),
        migrations.AddField(
            model_name='discount',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Набор пар ключ-значение для хранения дополнительной информации о купоне.', null=True, verbose_name='Метаданные'),
        ),
        migrations.AddField(
            model_name='discount',
            name='percent_off',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Значение от 0 до 100. Если указано, то amount_off не должно быть установлено.', max_digits=5, null=True, verbose_name='Скидка в процентах'),
        ),
        migrations.AddField(
            model_name='tax',
            name='inclusive',
            field=models.BooleanField(default=False, verbose_name='Добавляется ли процент налога к общей сумме или включается в нее'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
